# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 3.7
python: 3.7

# Install dependencies
install:
  - pip install -U pipenv
  - pipenv install

# Run the unit test
script:
  - coverage run test_dolar.py

# Push the results back to codecov
after_success:
  - codecov
